import { StyleSheet } from "react-native";
import { palette, radius, shadow } from "../theme";

export const s = StyleSheet.create({
  screen: { flex: 1, backgroundColor: palette.bg },
  top: {
    paddingHorizontal: 24,
    paddingVertical: 18,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    ...shadow.soft,
  },
  brand: {
    fontSize: 28,
    fontWeight: "800",
    letterSpacing: -1,
    color: "#FFFFFF",
  },
  dot: { color: "#FFF06A" },
  liveDot: { width: 8, height: 8, borderRadius: 4 },
  headerTag: {
    fontSize: 10,
    color: "rgba(255,255,255,0.9)",
    letterSpacing: 1,
    fontWeight: "700",
    maxWidth: 160,
  },
  tag: {
    fontSize: 10,
    color: palette.textDim,
    letterSpacing: 1,
    fontWeight: "700",
    maxWidth: 160,
  },
  content: {
    padding: 24,
    gap: 18,
    width: "100%",
    maxWidth: 660,
    alignSelf: "center",
    paddingBottom: 48,
  },
  eyebrow: {
    fontSize: 10,
    letterSpacing: 1.3,
    color: palette.textFaint,
    fontWeight: "700",
  },
  hero: {
    fontSize: 46,
    letterSpacing: -1.8,
    color: palette.text,
    fontWeight: "800",
  },
  title: {
    fontSize: 32,
    letterSpacing: -0.8,
    color: palette.text,
    fontWeight: "700",
  },
  body: { fontSize: 15, lineHeight: 24, color: palette.textDim },
  caption: { fontSize: 12, lineHeight: 19, color: palette.textFaint },
  levelMeta: {
    alignSelf: "flex-start",
    borderRadius: radius.pill,
    borderWidth: 1,
    backgroundColor: palette.surface,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  levelMetaText: { fontSize: 12, fontWeight: "700" },
  levelBadge: {
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    borderRadius: radius.lg,
    padding: 16,
    gap: 4,
  },
  levelBadgeLabel: {
    fontSize: 10,
    letterSpacing: 1.2,
    fontWeight: "800",
    color: palette.textFaint,
  },
  levelBadgeValue: { fontSize: 26, fontWeight: "800" },
  levelBadgeMax: { fontSize: 14, fontWeight: "700", color: palette.textFaint },
  section: { fontSize: 18, fontWeight: "700", color: palette.text },
  member: { fontSize: 16, fontWeight: "600", color: palette.text },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  tabs: {
    flexDirection: "row",
    padding: 4,
    borderRadius: radius.md,
    backgroundColor: palette.surface,
    gap: 3,
  },
  tab: { flex: 1, paddingVertical: 14, alignItems: "center", borderRadius: 9 },
  tabActive: { backgroundColor: palette.surfaceRaised },
  tabText: { fontSize: 13, color: palette.textDim, fontWeight: "600" },
  tabTextActive: { color: palette.text },
  presencePill: {
    borderRadius: radius.pill,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  presenceOn: { backgroundColor: "#DCFCE7" },
  presenceOff: { backgroundColor: "#FEE2E2" },
  game: {
    padding: 16,
    borderWidth: 1.5,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    borderRadius: radius.lg,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  symbol: {
    height: 48,
    width: 48,
    borderRadius: radius.md,
    alignItems: "center",
    justifyContent: "center",
    ...shadow.soft,
  },
  symbolText: { fontSize: 22, fontWeight: "800" },
  radioDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: palette.border,
  },
  input: {
    fontFamily: "System",
    borderWidth: 1,
    borderColor: palette.borderActive,
    borderRadius: radius.sm,
    backgroundColor: palette.surface,
    padding: 16,
    fontSize: 16,
    color: palette.text,
  },
  roomCode: {
    fontSize: 34,
    letterSpacing: 4,
    fontWeight: "700",
    color: palette.cyan,
    textAlign: "center",
  },
  score: {
    fontSize: 80,
    fontWeight: "800",
    color: palette.text,
    textAlign: "center",
  },
  error: {
    color: "#B42318",
    backgroundColor: "#FEE4E2",
    padding: 14,
    borderRadius: radius.sm,
    lineHeight: 21,
  },
  round: { gap: 24, paddingVertical: 16 },
  timerChip: {
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: radius.pill,
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  timerChipText: { fontSize: 12, fontWeight: "800", color: palette.textDim },
  question: {
    fontSize: 32,
    fontWeight: "700",
    color: palette.text,
    textAlign: "center",
    paddingVertical: 24,
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    justifyContent: "space-between",
  },
  option: {
    width: "47%",
    minHeight: 90,
    backgroundColor: palette.surfaceRaised,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: radius.lg,
    justifyContent: "center",
    alignItems: "center",
  },
  optionText: { fontSize: 30, color: palette.text, fontWeight: "700" },
  progress: {
    height: 6,
    backgroundColor: palette.surface,
    borderRadius: 6,
    overflow: "hidden",
  },
  progressFill: { height: 6, borderRadius: 6 },
  stats: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: radius.lg,
    padding: 18,
    gap: 8,
    ...shadow.soft,
  },
  statValue: { color: palette.text, fontSize: 20, fontWeight: "800" },
});
