import { StyleSheet } from "react-native";
import { palette, radius, shadow } from "../theme";

export const s = StyleSheet.create({
  // Veredito da rodada (Round.tsx): a opção certa e a que foi tocada ficam
  // marcadas com símbolo além da cor — há quem não distinga verde de vermelho.
  optionRight: { borderWidth: 3, borderColor: palette.green },
  optionWrong: { borderWidth: 3, borderColor: palette.red },
  goalTrack: {
    height: 8,
    borderRadius: 4,
    backgroundColor: palette.surfaceAlt,
    overflow: "hidden",
  },
  goalFill: { height: 8, borderRadius: 4 },
  resultLead: { fontSize: 16, fontWeight: "800", color: palette.text, lineHeight: 24 },
  verdict: { fontSize: 15, fontWeight: "800", lineHeight: 22, textAlign: "center" },
  optionRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  mark: { fontSize: 20, fontWeight: "900" },
  markOverPiece: {
    position: "absolute",
    top: -6,
    right: -4,
    fontSize: 14,
    fontWeight: "900",
    color: palette.text,
  },
  screen: { flex: 1, backgroundColor: palette.bg },
  top: {
    paddingHorizontal: 24,
    paddingVertical: 18,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    ...shadow.soft,
  },
  brand: {
    fontSize: 28,
    fontWeight: "800",
    letterSpacing: -1,
    color: "#FFFFFF",
  },
  dot: { color: "#FFF06A" },
  liveDot: { width: 8, height: 8, borderRadius: 4 },
  headerTag: {
    fontSize: 10,
    color: "rgba(255,255,255,0.9)",
    letterSpacing: 1,
    fontWeight: "700",
    maxWidth: 160,
  },
  tag: {
    fontSize: 10,
    color: palette.textDim,
    letterSpacing: 1,
    fontWeight: "700",
    maxWidth: 160,
  },
  content: {
    padding: 24,
    gap: 18,
    width: "100%",
    maxWidth: 660,
    alignSelf: "center",
    paddingBottom: 48,
  },
  eyebrow: {
    fontSize: 10,
    letterSpacing: 1.3,
    color: palette.textFaint,
    fontWeight: "700",
  },
  hero: {
    fontSize: 40,
    letterSpacing: -1.8,
    color: palette.text,
    fontWeight: "800",
  },
  heroBlock: { gap: 7, paddingVertical: 4 },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    gap: 12,
  },
  gameGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  gameGridItem: { width: "48%", flexGrow: 1 },
  gameTile: {
    minHeight: 132,
    padding: 14,
    gap: 9,
    borderWidth: 1.5,
    borderColor: palette.border,
    borderRadius: radius.lg,
    backgroundColor: palette.surface,
  },
  gameTileName: {
    color: palette.text,
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "800",
  },
  symbolSmall: {
    width: 38,
    height: 38,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
  },
  symbolTextSmall: { fontSize: 18, fontWeight: "900" },
  selectedLabel: { fontSize: 8, fontWeight: "900", letterSpacing: 1 },
  playPanel: { gap: 12 },
  titleSmall: {
    fontSize: 24,
    fontWeight: "900",
    color: palette.text,
    letterSpacing: -0.5,
  },
  levelCompact: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: radius.pill,
  },
  levelCompactText: { fontSize: 11, fontWeight: "900" },
  rankLine: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 9,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
  },
  progressNote: { alignItems: "center", paddingVertical: 8 },
  title: {
    fontSize: 32,
    letterSpacing: -0.8,
    color: palette.text,
    fontWeight: "700",
  },
  body: { fontSize: 15, lineHeight: 24, color: palette.textDim },
  caption: { fontSize: 12, lineHeight: 19, color: palette.textFaint },
  levelMeta: {
    alignSelf: "flex-start",
    borderRadius: radius.pill,
    borderWidth: 1,
    backgroundColor: palette.surface,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  levelMetaText: { fontSize: 12, fontWeight: "700" },
  levelBadge: {
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    borderRadius: radius.lg,
    padding: 16,
    gap: 4,
  },
  levelBadgeLabel: {
    fontSize: 10,
    letterSpacing: 1.2,
    fontWeight: "800",
    color: palette.textFaint,
  },
  levelBadgeValue: { fontSize: 26, fontWeight: "800" },
  levelBadgeMax: { fontSize: 14, fontWeight: "700", color: palette.textFaint },
  section: { fontSize: 18, fontWeight: "700", color: palette.text },
  member: { fontSize: 16, fontWeight: "600", color: palette.text },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  tabs: {
    flexDirection: "row",
    padding: 4,
    borderRadius: radius.md,
    backgroundColor: palette.surface,
    gap: 3,
  },
  tab: { flex: 1, paddingVertical: 14, alignItems: "center", borderRadius: 9 },
  tabActive: { backgroundColor: palette.surfaceRaised },
  tabText: { fontSize: 13, color: palette.textDim, fontWeight: "600" },
  tabTextActive: { color: palette.text },
  presencePill: {
    borderRadius: radius.pill,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  presenceOn: { backgroundColor: "#DCFCE7" },
  presenceOff: { backgroundColor: "#FEE2E2" },
  // Sala de turma (Ticket 30) — acima de ~6 membros, o lobby/placar trocam
  // a lista de uma linha por membro por um grid compacto, senão vira uma
  // lista longa demais pra rolar numa turma de 30.
  memberGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  memberGridItem: {
    flexBasis: "30%",
    minWidth: 88,
    alignItems: "center",
    gap: 2,
    padding: 8,
    borderRadius: radius.sm,
    backgroundColor: palette.surfaceAlt,
  },
  memberGridName: {
    fontSize: 12,
    fontWeight: "700",
    color: palette.text,
    textAlign: "center",
  },
  memberGridDetail: {
    fontSize: 11,
    fontWeight: "600",
    color: palette.textFaint,
    textAlign: "center",
  },
  presenceTextOn: { color: palette.green },
  presenceTextOff: { color: palette.red },
  game: {
    padding: 16,
    borderWidth: 1.5,
    borderColor: palette.border,
    backgroundColor: palette.surface,
    borderRadius: radius.lg,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  symbol: {
    height: 48,
    width: 48,
    borderRadius: radius.md,
    alignItems: "center",
    justifyContent: "center",
    ...shadow.soft,
  },
  symbolText: { fontSize: 22, fontWeight: "800" },
  radioDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: palette.border,
  },
  input: {
    fontFamily: "System",
    borderWidth: 1,
    borderColor: palette.borderActive,
    borderRadius: radius.sm,
    backgroundColor: palette.surface,
    padding: 16,
    fontSize: 16,
    color: palette.text,
  },
  roomCode: {
    fontSize: 34,
    letterSpacing: 4,
    fontWeight: "700",
    color: palette.cyan,
    textAlign: "center",
  },
  score: {
    fontSize: 80,
    fontWeight: "800",
    color: palette.text,
    textAlign: "center",
  },
  error: {
    color: "#B42318",
    backgroundColor: "#FEE4E2",
    padding: 14,
    borderRadius: radius.sm,
    lineHeight: 21,
  },
  round: { gap: 24, paddingVertical: 16 },
  timerChip: {
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: radius.pill,
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  timerChipText: { fontSize: 12, fontWeight: "800", color: palette.textDim },
  comboChip: {
    backgroundColor: "#FFF4E0",
    borderWidth: 1,
    borderColor: palette.amber,
    borderRadius: radius.pill,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  comboChipText: { fontSize: 12, fontWeight: "800", color: palette.amber },
  question: {
    fontSize: 32,
    fontWeight: "700",
    color: palette.text,
    textAlign: "center",
    paddingVertical: 24,
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    justifyContent: "space-between",
  },
  option: {
    width: "47%",
    minHeight: 90,
    backgroundColor: palette.surfaceRaised,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: radius.lg,
    justifyContent: "center",
    alignItems: "center",
  },
  optionText: { fontSize: 30, color: palette.text, fontWeight: "700" },
  progress: {
    height: 6,
    backgroundColor: palette.surface,
    borderRadius: 6,
    overflow: "hidden",
  },
  progressFill: { height: 6, borderRadius: 6 },
  stats: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: radius.lg,
    padding: 18,
    gap: 8,
    ...shadow.soft,
  },
  statValue: { color: palette.text, fontSize: 20, fontWeight: "800" },
});
