import { StyleSheet } from "react-native";
import { palette, radius, shadow } from "../theme";

export const s = StyleSheet.create({
  screen: { flex: 1, backgroundColor: palette.bg },
  top: {
    padding: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    ...shadow.soft,
  },
  brand: { color: "#FFFFFF", fontSize: 23, fontWeight: "800" },
  headerLabel: {
    color: "rgba(255,255,255,0.9)",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1,
  },
  headerAccent: { color: "#FFFFFF", fontSize: 14, fontWeight: "800" },
  liveDot: { width: 8, height: 8, borderRadius: 4 },
  row: { flexDirection: "row", alignItems: "center", gap: 8 },
  content: {
    padding: 24,
    gap: 18,
    paddingBottom: 40,
    width: "100%",
    maxWidth: 620,
    alignSelf: "center",
  },
  hero: { color: palette.text, fontSize: 38, fontWeight: "800" },
  heading: { color: palette.text, fontSize: 19, fontWeight: "700" },
  muted: { color: palette.textDim, fontSize: 14, lineHeight: 22 },
  label: {
    color: palette.textDim,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1,
  },
  accent: { color: palette.cyan, fontSize: 14, fontWeight: "800" },
  error: {
    color: "#B42318",
    backgroundColor: "#FEE4E2",
    padding: 12,
    borderRadius: radius.sm,
    lineHeight: 22,
  },
  input: {
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 17,
    borderRadius: radius.md,
    color: palette.text,
    fontSize: 17,
    fontFamily: "System",
  },
  dailyCard: {
    borderWidth: 1,
    borderColor: palette.borderActive,
    padding: 22,
    borderRadius: radius.md,
    gap: 10,
    ...shadow.soft,
  },
  dailyTitle: { color: palette.text, fontSize: 25, fontWeight: "700" },
  dailyIcon: { color: palette.text, fontSize: 25, fontWeight: "700" },
  dailyDone: { color: palette.green, fontSize: 15, fontWeight: "800" },
  achievementGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 12,
  },
  achievement: {
    width: "47%",
    minHeight: 145,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: radius.lg,
    padding: 16,
    gap: 7,
  },
  achievementLocked: { opacity: 0.45 },
  achievementIcon: { fontSize: 30 },
  achievementName: { color: palette.text, fontSize: 15, fontWeight: "800" },
  achievementDesc: { color: palette.textDim, fontSize: 12, lineHeight: 17 },
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,.78)",
    justifyContent: "center",
    padding: 24,
  },
  recoveryCard: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: radius.md,
    padding: 24,
    gap: 14,
  },
  recoveryCode: {
    color: palette.cyan,
    fontSize: 18,
    lineHeight: 28,
    fontWeight: "700",
    letterSpacing: 1.5,
    textAlign: "center",
  },
  between: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    gap: 12,
  },
  // Cabeçalho do perfil (Ticket 34) — gradients.hero já é o fundo do
  // AppHeader logo acima; usar cardActive aqui em vez de repetir o mesmo
  // gradiente forte duas vezes seguidas na tela.
  heroCard: {
    alignItems: "center",
    gap: 8,
    padding: 20,
    borderRadius: radius.xl,
    ...shadow.soft,
  },
  heroName: { fontSize: 24, fontWeight: "900", color: palette.text },
  heroCompetitive: { fontSize: 13, fontWeight: "700", color: palette.textDim },
  // Nível/XP/moedas (Ticket 35) — eram uma única linha de texto corrida.
  statRow: { flexDirection: "row", gap: 10 },
  statChip: {
    flex: 1,
    alignItems: "center",
    gap: 2,
    paddingVertical: 12,
    borderRadius: radius.md,
    backgroundColor: palette.surfaceAlt,
  },
  statValue: { fontSize: 18, fontWeight: "900", color: palette.text },
  statLabel: { fontSize: 11, fontWeight: "700", color: palette.textFaint },
  track: {
    height: 6,
    borderRadius: 5,
    backgroundColor: palette.surfaceRaised,
    overflow: "hidden",
  },
  fill: { height: 6, backgroundColor: palette.cyan },
  choices: { flexDirection: "row", gap: 8 },
  choice: {
    flex: 1,
    padding: 12,
    borderRadius: radius.md,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    alignItems: "center",
  },
  selected: {
    backgroundColor: palette.surfaceRaised,
    borderColor: palette.borderActive,
  },
  dark: { color: palette.text, fontSize: 14 },
  game: { padding: 24, borderRadius: radius.md, borderWidth: 1, gap: 10 },
  gameIcon: {
    width: 40,
    height: 40,
    borderRadius: radius.sm,
    alignItems: "center",
    justifyContent: "center",
  },
  gameIconText: { fontSize: 18, fontWeight: "800" },
  gameTitle: { fontSize: 21, fontWeight: "700", color: palette.text },
  gameFoot: {
    fontWeight: "800",
    fontSize: 12,
    marginTop: 10,
  },
  rankRow: {
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: palette.border,
    paddingHorizontal: 16,
  },
  nav: {
    flexDirection: "row",
    justifyContent: "space-around",
    padding: 20,
    borderTopWidth: 1,
    borderColor: palette.border,
  },
  round: { flex: 1, padding: 24, justifyContent: "center", gap: 24 },
  big: {
    color: palette.text,
    fontSize: 80,
    fontWeight: "800",
    textAlign: "center",
    fontVariant: ["tabular-nums"],
  },
  reflex: {
    height: 300,
    borderRadius: radius.xl,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  reflexText: {
    fontSize: 27,
    fontWeight: "700",
    color: palette.text,
    textAlign: "center",
  },
  grid: {
    width: "100%",
    maxWidth: 400,
    alignSelf: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 12,
  },
  tile: {
    width: "47%",
    aspectRatio: 1,
    borderRadius: radius.md,
    justifyContent: "center",
    alignItems: "center",
  },
  tileText: { fontSize: 35, fontWeight: "700", color: palette.text },
});
